name: Update TryHackMe Badge

on:
  schedule:
    # Runs every thirty minutes
    - cron: '*/30 * * * *'
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow playwright

      - name: Install Playwright browsers
        run: |
          python -m playwright install chromium

      - name: Update TryHackMe badge
        run: python update_badge.py

      - name: Move badge image to docs folder
        run: |
          mkdir -p docs
          cp tryhackme_badge.png docs/

      - name: Debug information
        run: |
          ls -la
          if [ -f tryhackme_badge.png ]; then
            echo "Badge file exists with size: $(du -h tryhackme_badge.png)"
            file tryhackme_badge.png
          else
            echo "Badge file does not exist!"
          fi

          if [ -f debug_full_page.png ]; then
            echo "Debug screenshot exists with size: $(du -h debug_full_page.png)"
            # Include the debug screenshot in the commit
            git add debug_full_page.png
          fi

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit TryHackMe Badge
          file_pattern: "tryhackme_badge.png docs/tryhackme_badge.png"
